services:
  - type: web
    name: lms-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000

  - type: web
    name: lms-frontend
    runtime: static
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
